// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4wCBSpSHRqB5f9KMWJmbtdjW710pMbbI',
    appId: '1:639831898399:android:afa265e055fbbc2e85d82a',
    messagingSenderId: '639831898399',
    projectId: 'depi-sports-project',
    storageBucket: 'depi-sports-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMWbspXpvCfCkW0PwDDxt18TRmMtAqJY',
    appId: '1:639831898399:ios:b50d641e1c6c9a0485d82a',
    messagingSenderId: '639831898399',
    projectId: 'depi-sports-project',
    storageBucket: 'depi-sports-project.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP-KCu96ppYBSleP46oULUKvAVhOT8FKM',
    appId: '1:639831898399:web:7da2c944f98edf6585d82a',
    messagingSenderId: '639831898399',
    projectId: 'depi-sports-project',
    authDomain: 'depi-sports-project.firebaseapp.com',
    storageBucket: 'depi-sports-project.appspot.com',
    measurementId: 'G-SYBWN2Z8VZ',
  );
}
